{{- if and .Values.executionStorageClassName .Values.consensusStorageClassName }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.executionStorageClassName }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
parameters:
  path: /data/{{ .Values.executionStorageClassName }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.consensusStorageClassName }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
parameters:
  path: /data/{{ .Values.consensusStorageClassName }}
{{- end }}
