FROM rust:1.93-bookworm AS builder

WORKDIR /build

COPY reth-erc8004-indexer/Cargo.toml reth-erc8004-indexer/Cargo.toml
COPY reth-erc8004-indexer/src reth-erc8004-indexer/src

RUN cargo build --release --manifest-path reth-erc8004-indexer/Cargo.toml

FROM ghcr.io/paradigmxyz/reth:v1.11.1

COPY --from=builder /build/target/release/reth /usr/local/bin/reth
