FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /job-broker ./cmd/job-broker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /job-broker /job-broker
ENTRYPOINT ["/job-broker"]
