package schemas

import (
	_ "embed"

	"github.com/ObolNetwork/obol-stack/internal/buyprompts"
)

// ServiceCatalogJSONSchema is the JSON Schema for the public
// /api/services.json catalog served by sellers.
//
//go:embed service-catalog.schema.json
var ServiceCatalogJSONSchema string

// ServiceCatalogEntry is the JSON representation of a ServiceOffer for the
// public storefront and for machine consumers constructing x402 payments.
//
// Stable wire schema: agents rely on asset.eip712Domain.name and
// asset.eip712Domain.version to construct ERC-3009 or Permit2 signatures.
// Do not rename fields without coordinating with buy.py and downstream agents.
type ServiceCatalogEntry struct {
	Name             string               `json:"name"`
	Namespace        string               `json:"namespace"`
	Type             string               `json:"type"`
	Model            string               `json:"model,omitempty"`
	Endpoint         string               `json:"endpoint"`
	Price            string               `json:"price"`
	PriceRaw         string               `json:"priceRaw,omitempty"`
	PriceUnit        string               `json:"priceUnit,omitempty"`
	PriceAtomicUnits string               `json:"priceAtomicUnits,omitempty"`
	PayTo            string               `json:"payTo"`
	Network          string               `json:"network"`
	CAIP2Network     string               `json:"caip2Network,omitempty"`
	ChainID          int64                `json:"chainId,omitempty"`
	Asset            *ServiceCatalogAsset `json:"asset,omitempty"`
	Description      string               `json:"description"`
	// DescriptionHTML is the sanitized HTML rendering of Description
	// (markdown subset). Produced ONLY by internal/storefront/richtext.go;
	// consumers may inject it verbatim. Absent on catalogs from
	// pre-richtext controllers — fall back to the plain Description.
	DescriptionHTML string `json:"descriptionHtml,omitempty"`
	// Skills are the OASF / buy-x402 skill names this offer advertises.
	// For type=agent offers it mirrors AgentResolution.Skills (the
	// resolved allow-list from the linked Agent CR); for non-agent
	// offers it mirrors spec.registration.skills. Surfaced as pills on
	// the storefront ServiceCard.
	Skills []string `json:"skills,omitempty"`

	// Payments is every accepted payment option for this offer (one per
	// currency/network). Always has at least one entry; payments[0] mirrors
	// the flat Price/PayTo/Network/Asset fields above (kept for consumers
	// predating multi-currency). The storefront renders one pay-row per entry.
	Payments []ServiceCatalogPaymentOption `json:"payments,omitempty"`

	// Category groups the offer into a named storefront section (e.g.
	// "demo"). Empty means the default/uncategorized section. Demo services
	// are just category="demo" — no special-casing. Mirrors
	// ServiceOffer.spec.listing.category.
	Category string `json:"category,omitempty"`

	// Weight orders offers within a category on the storefront: higher sorts
	// earlier. Mirrors ServiceOffer.spec.listing.weight.
	Weight int `json:"weight,omitempty"`

	// RegistrationPending is true when the offer is operationally ready
	// (route published, payment gate active, upstream healthy) but its
	// ERC-8004 on-chain registration tx hasn't landed yet. The storefront
	// should surface these with a "registration pending" badge so consumers
	// know the offer is usable for x402 payments today, even though
	// ERC-8004 discovery via the chain still resolves to the prior state.
	RegistrationPending bool `json:"registrationPending,omitempty"`

	// DrainEndsAt is the RFC3339 timestamp at which the offer's
	// HTTPRoute will be removed. Set ONLY when the offer is draining.
	// Consumers detect a drain window with `if (entry.drainEndsAt)`:
	// active offers serialize without this field, so the schema stays
	// purely additive vs. pre-drain catalogs. Buyers SHOULD migrate to
	// alternative providers before this time.
	DrainEndsAt string `json:"drainEndsAt,omitempty"`

	// Buy is the canonical buyer-instruction block for this offer: the
	// machine-readable call shape (method/path/body/streaming) plus
	// copy-paste prompts keyed by buyer-software kind (obol-agent,
	// generic-llm, cli). Generated by internal/buyprompts — the single
	// authoring point — and rendered verbatim by the storefront so buyer
	// instructions cannot drift between surfaces.
	Buy *buyprompts.Block `json:"buy,omitempty"`

	// OpenAPIPath is this offer's key in the /openapi.json `paths` object
	// (e.g. "/services/foo/v1/chat/completions"), so consumers can jump
	// from a catalog entry straight to its request/response schema without
	// scanning the whole spec.
	OpenAPIPath string `json:"openapiPath,omitempty"`

	// DocsPath is the site-relative deep link into the human API docs UI
	// for this offer's operation (e.g.
	// "/api#tag/agent/POST/services/foo/v1/chat/completions"). The anchor
	// format is renderer-specific (Scalar hash routing), so it's published
	// here rather than reconstructed by consumers.
	DocsPath string `json:"docsPath,omitempty"`
}

// ServiceCatalogPaymentOption is one accepted (price, payTo, network, asset)
// combination on an offer. Same fields as the entry's flat payment block,
// repeated once per advertised currency/network.
type ServiceCatalogPaymentOption struct {
	Price            string               `json:"price"`
	PriceRaw         string               `json:"priceRaw,omitempty"`
	PriceUnit        string               `json:"priceUnit,omitempty"`
	PriceAtomicUnits string               `json:"priceAtomicUnits,omitempty"`
	PayTo            string               `json:"payTo"`
	Network          string               `json:"network"`
	CAIP2Network     string               `json:"caip2Network,omitempty"`
	ChainID          int64                `json:"chainId,omitempty"`
	Asset            *ServiceCatalogAsset `json:"asset,omitempty"`
}

// ServiceCatalogAsset describes the settlement token resolved for a catalog
// entry. It mirrors the x402 asset metadata consumers need for signing.
type ServiceCatalogAsset struct {
	Address        string                      `json:"address,omitempty"`
	Symbol         string                      `json:"symbol,omitempty"`
	Decimals       int64                       `json:"decimals,omitempty"`
	TransferMethod string                      `json:"transferMethod,omitempty"`
	EIP712Domain   *ServiceCatalogEIP712Domain `json:"eip712Domain,omitempty"`
}

// ServiceCatalogEIP712Domain is the signing domain agents must use when
// pre-signing payment authorizations. This is not always the same as the
// human-readable token name returned by the token contract.
type ServiceCatalogEIP712Domain struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// StorefrontProfile is operator-set seller branding merged into
// /api/services.json by the controller.
type StorefrontProfile struct {
	DisplayName  string `json:"displayName"`
	Tagline      string `json:"tagline"`
	LogoURL      string `json:"logoUrl"`
	ContactEmail string `json:"contactEmail,omitempty"`

	// Theme is a preset name ("light", "dark", "obol"); empty means the
	// stack default (light). Applied to every seller-facing HTML surface.
	Theme string `json:"theme,omitempty"`
	// AccentColor optionally overrides the preset accent with a #hex value
	// (validated against a strict hex pattern before it reaches any CSS).
	AccentColor string `json:"accentColor,omitempty"`
	// FaviconURL follows the same forms as LogoURL (https://, /path, or
	// inline data:image/...;base64). Empty falls back to the logo.
	FaviconURL string `json:"faviconUrl,omitempty"`
	// OGImageURL is the link-preview image (og:image). Empty falls back to
	// the storefront's generated preview.
	OGImageURL string `json:"ogImageUrl,omitempty"`
	// Description is longer-form seller copy (markdown subset). Publishing
	// surfaces render it as plain text until the richtext pipeline lands.
	Description string `json:"description,omitempty"`
	// CustomCSS is operator-authored CSS injected after the theme tokens
	// on every seller HTML surface (the styling escape hatch on top of
	// the stable data-obol/class hooks). Size-capped and validated
	// against style-element breakout at set time; renderers re-check
	// before injection.
	CustomCSS string `json:"customCss,omitempty"`
}

// ServiceCatalogSchemaVersion is the current version of the
// /api/services.json envelope. Bump only on a breaking change to the wire
// shape; additive fields do not bump the version. Integrators/indexers use
// it to detect incompatible catalogs instead of guessing from field shapes.
const ServiceCatalogSchemaVersion = "1"

// ServiceCatalog is the public /api/services.json envelope.
type ServiceCatalog struct {
	// SchemaVersion identifies the envelope wire version (currently "1").
	// Always populated by the controller; consumers should treat an absent
	// field as a legacy pre-versioning catalog.
	SchemaVersion string                `json:"schemaVersion"`
	DisplayName   string                `json:"displayName"`
	Tagline       string                `json:"tagline"`
	LogoURL       string                `json:"logoUrl"`
	Services      []ServiceCatalogEntry `json:"services"`

	// Theme is the operator-selected preset name (always populated by
	// current controllers; empty on catalogs from older releases).
	Theme string `json:"theme,omitempty"`
	// ThemeVars is the resolved token→hex map for Theme (accent override
	// already applied), so consumers can style without knowing the presets.
	// Keys are the bare token names ("bg01", "green", ...).
	ThemeVars map[string]string `json:"themeVars,omitempty"`
	// FaviconURL / OGImageURL / Description mirror StorefrontProfile.
	FaviconURL  string `json:"faviconUrl,omitempty"`
	OGImageURL  string `json:"ogImageUrl,omitempty"`
	Description string `json:"description,omitempty"`
	// DescriptionHTML is the sanitized HTML rendering of Description —
	// same contract as ServiceCatalogEntry.DescriptionHTML.
	DescriptionHTML string `json:"descriptionHtml,omitempty"`
	// CustomCSS mirrors StorefrontProfile.CustomCSS for the storefront UI.
	CustomCSS string `json:"customCss,omitempty"`
}
