// Package walletbackup is the runtime-agnostic core of `obol agent wallet
// backup` / `restore`. It owns the on-disk backup wire format, the
// AES-256-GCM encryption envelope, and the helpers that read/write the
// keystore password from values-remote-signer.yaml. Per-runtime callers
// (internal/openclaw, internal/hermes) compose these primitives with their
// own deployDir/keystoreDir conventions and namespace-specific cluster apply
// steps. The on-disk format must round-trip across runtimes, so a backup
// taken from an OpenClaw instance can restore into a Hermes one and vice
// versa.
package walletbackup

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/ObolNetwork/obol-stack/internal/ui"
	"golang.org/x/crypto/scrypt"
	"gopkg.in/yaml.v3"
)

// Magic is the 4-byte prefix of an encrypted backup file.
var Magic = []byte("OBOL")

// Version is the current backup-format version. Bumping requires a parallel
// bump in Decode's accepted-versions check.
const Version = 1

const (
	scryptN     = 262144
	scryptR     = 8
	scryptP     = 1
	scryptDKLen = 32
)

// File is the JSON shape of a wallet backup. One backup may carry multiple
// wallets; today both runtimes write a single-wallet file.
type File struct {
	Version  int      `json:"version"`
	Instance string   `json:"instance"`
	Wallets  []Wallet `json:"wallets"`
}

// Wallet holds a single wallet's backup data — enough to restore both the
// keystore JSON on disk and the keystore password the remote-signer needs.
type Wallet struct {
	Address          string          `json:"address"`
	PublicKey        string          `json:"publicKey"`
	KeystoreUUID     string          `json:"keystoreUUID"`
	CreatedAt        string          `json:"createdAt"`
	Keystore         json.RawMessage `json:"keystore"`
	KeystorePassword string          `json:"keystorePassword"`
}

// Encode marshals a backup to bytes. If passphrase is non-empty, it returns
// an encrypted blob; otherwise it returns the indented JSON. The second
// return value reports which form was emitted.
func Encode(f *File, passphrase string) ([]byte, bool, error) {
	plain, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return nil, false, fmt.Errorf("marshal backup: %w", err)
	}
	if passphrase == "" {
		return plain, false, nil
	}
	enc, err := Encrypt(plain, passphrase)
	if err != nil {
		return nil, false, err
	}
	return enc, true, nil
}

// Decode parses raw bytes into a File. If the input starts with the OBOL
// magic, passphrase is required; otherwise it must be empty (or is ignored).
func Decode(data []byte, passphrase string) (*File, error) {
	var plain []byte
	if IsEncrypted(data) {
		if passphrase == "" {
			return nil, errors.New("passphrase required for encrypted backup")
		}
		dec, err := Decrypt(data, passphrase)
		if err != nil {
			return nil, fmt.Errorf("decryption failed (wrong passphrase?): %w", err)
		}
		plain = dec
	} else {
		plain = data
	}

	var f File
	if err := json.Unmarshal(plain, &f); err != nil {
		return nil, fmt.Errorf("invalid backup file: %w", err)
	}
	if f.Version != Version {
		return nil, fmt.Errorf("unsupported backup version %d (expected %d)", f.Version, Version)
	}
	if len(f.Wallets) == 0 {
		return nil, errors.New("backup contains no wallets")
	}
	return &f, nil
}

// IsEncrypted reports whether data carries the OBOL magic prefix.
func IsEncrypted(data []byte) bool {
	if len(data) < len(Magic) {
		return false
	}
	return string(data[:len(Magic)]) == string(Magic)
}

// PromptPassphrase resolves a passphrase for backup. If the caller already
// passed --passphrase explicitly, hasFlag=true short-circuits the prompt
// (even when flagValue is the empty string, which means "no encryption").
func PromptPassphrase(flagValue string, hasFlag bool, u *ui.UI) (string, error) {
	if hasFlag {
		return flagValue, nil
	}
	pass, err := u.SecretInput("Backup passphrase (empty for no encryption)")
	if err != nil {
		return "", fmt.Errorf("failed to read passphrase: %w", err)
	}
	if pass == "" {
		return "", nil
	}
	confirm, err := u.SecretInput("Confirm passphrase")
	if err != nil {
		return "", fmt.Errorf("failed to read confirmation: %w", err)
	}
	if pass != confirm {
		return "", errors.New("passphrases do not match")
	}
	return pass, nil
}

// ReadKeystorePassword extracts keystorePassword.value from
// values-remote-signer.yaml under deployDir. Both Hermes and OpenClaw write
// the same shape, generated by their respective generateRemoteSignerValues.
func ReadKeystorePassword(deployDir string) (string, error) {
	data, err := os.ReadFile(filepath.Join(deployDir, "values-remote-signer.yaml"))
	if err != nil {
		return "", err
	}
	var values struct {
		KeystorePassword struct {
			Value string `yaml:"value"`
		} `yaml:"keystorePassword"`
	}
	if err := yaml.Unmarshal(data, &values); err != nil {
		return "", fmt.Errorf("failed to parse values-remote-signer.yaml: %w", err)
	}
	if values.KeystorePassword.Value == "" {
		return "", errors.New("keystorePassword.value not found in values-remote-signer.yaml")
	}
	return values.KeystorePassword.Value, nil
}

// WriteValuesRemoteSigner writes the rendered values-remote-signer.yaml to
// deployDir. Callers pass the runtime-specific rendered content (the YAML
// shape is identical across runtimes, but the comment header differs).
func WriteValuesRemoteSigner(deployDir, content string) error {
	return os.WriteFile(filepath.Join(deployDir, "values-remote-signer.yaml"), []byte(content), 0o600)
}

// Encrypt wraps plaintext with AES-256-GCM under a scrypt-derived key.
// Layout: magic(4) | version(1) | salt(32) | nonce(12) | ciphertext+tag.
// Exported so callers (and crypto-only tests) can exercise the envelope
// without going through Encode's JSON marshalling step.
func Encrypt(plaintext []byte, passphrase string) ([]byte, error) {
	salt := make([]byte, 32)
	if _, err := rand.Read(salt); err != nil {
		return nil, fmt.Errorf("salt generation: %w", err)
	}
	key, err := scrypt.Key([]byte(passphrase), salt, scryptN, scryptR, scryptP, scryptDKLen)
	if err != nil {
		return nil, fmt.Errorf("scrypt key derivation: %w", err)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("gcm: %w", err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, fmt.Errorf("nonce generation: %w", err)
	}
	ciphertext := gcm.Seal(nil, nonce, plaintext, nil)
	out := make([]byte, 0, len(Magic)+1+len(salt)+len(nonce)+len(ciphertext))
	out = append(out, Magic...)
	out = append(out, byte(Version))
	out = append(out, salt...)
	out = append(out, nonce...)
	out = append(out, ciphertext...)
	return out, nil
}

// Decrypt reverses Encrypt for the same passphrase, returning an error if
// the magic, version, or AEAD tag fails to verify.
func Decrypt(data []byte, passphrase string) ([]byte, error) {
	minLen := len(Magic) + 1 + 32 + 12
	if len(data) < minLen {
		return nil, errors.New("encrypted file too short")
	}
	off := 0
	if string(data[off:off+len(Magic)]) != string(Magic) {
		return nil, errors.New("not an encrypted backup file")
	}
	off += len(Magic)
	if data[off] != byte(Version) {
		return nil, fmt.Errorf("unsupported encryption version %d", data[off])
	}
	off++
	salt := data[off : off+32]
	off += 32
	key, err := scrypt.Key([]byte(passphrase), salt, scryptN, scryptR, scryptP, scryptDKLen)
	if err != nil {
		return nil, fmt.Errorf("scrypt key derivation: %w", err)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("gcm: %w", err)
	}
	nonceSize := gcm.NonceSize()
	if len(data) < off+nonceSize {
		return nil, errors.New("encrypted file too short for nonce")
	}
	nonce := data[off : off+nonceSize]
	off += nonceSize
	ciphertext := data[off:]
	plain, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("decryption failed: %w", err)
	}
	return plain, nil
}
