apiVersion: v1
kind: ConfigMap
metadata:
  name: mev-boost-config
  namespace: l1
data:
  network: "sepolia"
  relays: |
    https://0x845bd072b7cd566f02faeb0a4033ce9399e42839ced64e8b2adcfc859ed1e8e1a5a293336a49feac6d9a5edb779be53a@boost-relay-sepolia.flashbots.net