apiVersion: v1
kind: Service
metadata:
  name: mev-boost
  namespace: l1
  labels:
    app: mev-boost
spec:
  type: ClusterIP
  ports:
  - port: 18550
    targetPort: 18550
    protocol: TCP
    name: mev-boost
  selector:
    app: mev-boost