mode: auto

transport:
  protocol: "auto"

image:
  repository: cloudflare/cloudflared
  tag: "2026.10.0@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07"

metrics:
  address: "0.0.0.0:2000"

quickTunnel:
  url: "http://traefik.traefik.svc.cluster.local:80"

persistent:
  replicaCount: 1

management:
  configMapName: "cloudflared-management"
  modeKey: "management_mode"
  protocolKey: "transport_protocol"

remoteManaged:
  tokenSecretName: "cloudflared-tunnel-token"
  tokenSecretKey: "TUNNEL_TOKEN"

localManaged:
  secretName: "cloudflared-local-credentials"
  configMapName: "cloudflared-local-config"
  tunnelIDKey: "tunnel_id"
