mode: auto

transport:
  protocol: "auto"

image:
  repository: cloudflare/cloudflared
  tag: "2026.6.0@sha256:ba461b8aa9c042156dbd39c38657fe7431bafa063220eab8d5330a523863da9f"

metrics:
  address: "0.0.0.0:2000"

quickTunnel:
  url: "http://traefik.traefik.svc.cluster.local:80"

persistent:
  replicaCount: 2

management:
  configMapName: "cloudflared-management"
  modeKey: "management_mode"
  protocolKey: "transport_protocol"

remoteManaged:
  tokenSecretName: "cloudflared-tunnel-token"
  tokenSecretKey: "TUNNEL_TOKEN"

localManaged:
  secretName: "cloudflared-local-credentials"
  configMapName: "cloudflared-local-config"
  tunnelIDKey: "tunnel_id"
