mode: auto

image:
  repository: cloudflare/cloudflared
  tag: "2026.3.0"

metrics:
  address: "0.0.0.0:2000"

quickTunnel:
  url: "http://traefik.traefik.svc.cluster.local:80"

persistent:
  replicaCount: 2

management:
  configMapName: "cloudflared-management"
  modeKey: "management_mode"

remoteManaged:
  tokenSecretName: "cloudflared-tunnel-token"
  tokenSecretKey: "TUNNEL_TOKEN"

localManaged:
  secretName: "cloudflared-local-credentials"
  configMapName: "cloudflared-local-config"
  tunnelIDKey: "tunnel_id"
