# Nginx Ingress Controller default values (official kubernetes/ingress-nginx)

controller:
  replicaCount: 1

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  tolerations: []
