repositories:
  - name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts

values:
  # @enum mainnet,hoodi,testnet-aztec
  # @description Aztec networks to deploy
  - network: {{ env "AZTEC_NETWORK" | default "mainnet" }}

releases:
  # Create PVCs first - before the Ethereum node
  - name: aztec-pvcs
    namespace: aztec
    createNamespace: true
    chart: .
    values:
      # Pass only the values needed for PVC creation
      - network: '{{ .Values.network }}'

