apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expose-erpc
  namespace: l1
spec:
  ingressClassName: nginx
  rules:
    - host: obol.stack
      http:
        paths:
          - path: /rpc
            pathType: Prefix
            backend:
              service:
                name: rpc
                port:
                  number: 80