{{- if eq .Release.Name "ethereum-ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ethereum
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: obol.stack
    http:
      paths:
      - path: /ethereum/execution(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ethereum-execution-{{ .Values.executionClient }}-{{ .Values.network }}
            port:
              number: 8545
      - path: /ethereum/beacon(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ethereum-consensus-{{ .Values.consensusClient }}-{{ .Values.network }}
            port:
              number: 5052
{{- end }}
