apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: obol-stack-{{STACK_ID}}
servers: 1
agents: 0
image: rancher/k3s:v1.31.4-k3s1
volumes:
  - volume: {{DATA_DIR}}:/data
    nodeFilters:
      - all
  - volume: {{CONFIG_DIR}}/manifests:/var/lib/rancher/k3s/server/manifests/obol
    nodeFilters:
      - server:*
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "100s"
  k3s:
    extraArgs:
      - arg: --kubelet-arg=feature-gates=KubeletInUserNamespace=true
        nodeFilters:
          - server:*
      - arg: --kube-apiserver-arg=feature-gates=KubeletInUserNamespace=true
        nodeFilters:
          - server:*
      # Disable Traefik to use nginx instead
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  runtime:
    labels:
      - label: obol.cluster-id={{STACK_ID}}
        nodeFilters:
          - all
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
