// Package stackbackup implements `obol stack export` / `obol stack import`:
// a single archive capturing everything a running stack needs that is not
// regenerable from the obol binary — host config (helmfiles, values, sell
// offer descriptors, wallet metadata), agent data dirs (brains + remote-signer
// keystores), portable encrypted wallet backups, and the etcd-resident
// resources that drifted out of helmfile management (Agent CRs, ServiceOffers,
// LiteLLM/eRPC config mutations).
//
// Design notes live in plans/stack-export-import.md. The archive is a plain
// tar.gz with manifest.json as its first entry:
//
//	manifest.json          archive + obol version, stack id, component notes
//	config/...             $OBOL_CONFIG_DIR minus kubeconfig*/defaults/
//	data/<namespace>/...   agent data dirs (hermes-*, openclaw-*, agent-*)
//	wallets/...            walletbackup-format files (encrypted if passphrase)
//	cluster/...            stripped JSON dumps of CRs/ConfigMaps/Secrets
//
// The archive contains keystore passwords and provider API keys in the same
// plaintext form they already have on the host's disk — callers must treat it
// as a secret. The wallets/ component is additionally encryptable so wallet
// keys stay portable on their own.
package stackbackup

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ManifestVersion is the current archive format version. Import refuses
// archives with a different version.
const ManifestVersion = 1

// ManifestFileName is the archive's first entry.
const ManifestFileName = "manifest.json"

// Manifest describes an export archive.
type Manifest struct {
	Version     int         `json:"version"`
	ObolVersion string      `json:"obolVersion"`
	StackID     string      `json:"stackId,omitempty"`
	CreatedAt   string      `json:"createdAt"`
	ConfigDir   string      `json:"configDir"`
	DataDir     string      `json:"dataDir"`
	Components  []Component `json:"components"`
}

// Component records what one export component captured (or why it was
// skipped) so import and humans can reason about archive contents.
type Component struct {
	Name     string   `json:"name"`
	Included bool     `json:"included"`
	Notes    []string `json:"notes,omitempty"`
}

func (m *Manifest) component(name string) *Component {
	for i := range m.Components {
		if m.Components[i].Name == name {
			return &m.Components[i]
		}
	}
	return nil
}

// readStackID reads $OBOL_CONFIG_DIR/.stack-id. The file name is owned by
// internal/stack (stackIDFile); duplicated here because stack imports this
// package for the purge prompt, so we cannot import it back.
func readStackID(configDir string) string {
	data, err := os.ReadFile(filepath.Join(configDir, ".stack-id"))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

func decodeManifest(data []byte) (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("invalid manifest.json: %w", err)
	}
	if m.Version != ManifestVersion {
		return nil, fmt.Errorf("unsupported archive version %d (this obol understands %d)", m.Version, ManifestVersion)
	}
	return &m, nil
}

// dataNamespacePrefixes selects which $OBOL_DATA_DIR entries hold agent state
// worth backing up. Network chain data (ethereum-*, aztec-*) is deliberately
// excluded: it is large and re-syncable.
var dataNamespacePrefixes = []string{"hermes-", "openclaw-", "agent-"}

// selectDataNamespaces returns DataDir entries that look like agent
// namespaces (hermes-*, openclaw-*, agent-*).
func selectDataNamespaces(dataDir string) []string {
	entries, err := os.ReadDir(dataDir)
	if err != nil {
		return nil
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		for _, p := range dataNamespacePrefixes {
			if strings.HasPrefix(e.Name(), p) {
				out = append(out, e.Name())
				break
			}
		}
	}
	return out
}

// skipConfigEntry reports whether a ConfigDir-relative path is excluded from
// the config component: kubeconfigs are regenerated by `obol stack up`, and
// defaults/ is recopied from the embedded infrastructure on every up.
func skipConfigEntry(rel string) bool {
	if strings.HasPrefix(rel, "kubeconfig.yaml") {
		return true
	}
	return rel == "defaults" || strings.HasPrefix(rel, "defaults"+string(os.PathSeparator))
}
