repositories:
  - name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts

releases:
  - name: ethereum-node
    namespace: ethereum
    createNamespace: true
    chart: ethereum-helm-charts/ethereum-node
    version: 0.2.4
    values:
      - values.yaml
