export interface ServiceAsset {
  address?: string;
  symbol?: string;
  decimals?: number;
  transferMethod?: string;
}

// ServicePayment is one accepted (price, payTo, network, asset) option.
// Mirrors the catalog's ServiceCatalogPaymentOption. A service advertising
// several is paid in any one of them — the buyer picks.
export interface ServicePayment {
  price: string;
  priceRaw?: string;
  priceUnit?: string;
  payTo: string;
  network: string;
  asset?: ServiceAsset;
}

// ServiceBuyCallShape is the machine-readable request recipe published by the
// controller (internal/buyprompts) so buying software doesn't guess the
// path/method/streaming mode.
export interface ServiceBuyCallShape {
  method: string;
  path?: string;
  bodyKind: string;
  streaming?: boolean;
}

// ServiceBuy is the canonical buyer-instruction block. Prompts are keyed by
// buyer-software kind: "obol-agent" (paste into an Obol agent with the
// buy-x402 skill), "generic-llm" (paste into any other AI agent), "cli"
// (run from an obol-stack host). Rendering these verbatim — instead of
// composing storefront-local copy — is what keeps buy instructions from
// drifting between the storefront, the 402 page, and the catalog.
export interface ServiceBuy {
  callShape: ServiceBuyCallShape;
  prompts: Record<string, string>;
  example?: string;
}

export interface Service {
  name: string;
  namespace: string;
  type: string;
  model?: string;
  endpoint: string;
  price: string;
  priceRaw?: string;
  payTo: string;
  network: string;
  // asset is the resolved settlement token. Mirrors the controller's
  // ServiceCatalogAsset payload — when present, .symbol is the source of
  // truth for "what does this offer charge in" (e.g. "OBOL", "USDC"). The
  // legacy `network === "ethereum" ? "OBOL" : "USDC"` heuristic was wrong
  // for OBOL on base-sepolia and any non-mainnet OBOL deployment.
  asset?: ServiceAsset;
  description: string;
  // descriptionHtml is the sanitized HTML rendering of description
  // (markdown subset; sanitized by internal/storefront/richtext.go, the
  // single markdown→HTML path). Absent on catalogs from pre-richtext
  // controllers — fall back to the plain description.
  descriptionHtml?: string;
  // skills are the OASF / buy-x402 skill names this offer advertises.
  // For type=agent offers it mirrors AgentResolution.Skills (the
  // resolved allow-list from the linked Agent CR); for non-agent
  // offers it mirrors spec.registration.skills. Rendered as pills on
  // the ServiceCard, matching the 402 page.
  skills?: string[];
  // payments is every accepted payment option (one per currency/network).
  // payments[0] mirrors the flat price/network/payTo/asset fields. Absent on
  // catalogs predating multi-currency — fall back to the flat fields.
  payments?: ServicePayment[];
  // category groups the service into a storefront section (e.g. "demo").
  // Absent/empty means the default section. Mirrors spec.listing.category —
  // demo services are just category="demo", not a special case.
  category?: string;
  // weight orders services within a category; higher sorts earlier.
  weight?: number;
  // buy is the canonical buyer-instruction block generated by the
  // controller. Absent on catalogs from pre-buy-block controllers — the
  // card falls back to its legacy inline copy.
  buy?: ServiceBuy;
  // openapiPath is this service's key in /openapi.json's paths object,
  // used for deep links into the API docs.
  openapiPath?: string;
  // docsPath is the site-relative deep link into the API docs UI for this
  // service's operation (e.g. "/api#tag/agent/POST/services/x/v1/chat/completions").
  // Controller-published so the anchor format lives in one place.
  docsPath?: string;
}

export interface StorefrontProfile {
  displayName: string;
  tagline: string;
  logoUrl: string;
  // theme is the operator-selected preset name ("light" | "dark" | "obol").
  // Absent on catalogs from pre-theming controllers — treat as "light".
  theme?: string;
  // themeVars is the resolved token→hex map for the theme (accent override
  // already applied). Keys are bare token names ("bg01", "green", ...).
  themeVars?: Record<string, string>;
  // faviconUrl overrides the tab icon; empty falls back to the logo.
  faviconUrl?: string;
  // ogImageUrl overrides the link-preview image; empty uses the generated one.
  ogImageUrl?: string;
  // description is longer-form seller copy (markdown subset).
  description?: string;
  // descriptionHtml is its sanitized HTML rendering — same contract as
  // Service.descriptionHtml.
  descriptionHtml?: string;
  // customCss is operator CSS injected after the theme tokens (already
  // size-capped and breakout-checked by the controller; the layout guards
  // again before inlining).
  customCss?: string;
}
