# Helios Light Client Network
# Provides an Ethereum light client that can be used as an RPC endpoint

repositories:
  - name: obol
    url: https://obolnetwork.github.io/helm-charts/

releases:
  - name: helios
    namespace: helios-{{ .Values.id }}
    createNamespace: true
    chart: obol/helios
    version: 0.1.4
    values:
      - fullnameOverride: 'helios-{{ .Values.network }}'
      - helios:
          rpcBindIp: "0.0.0.0"
          rpcPort: 8545
          strictCheckpointAge: false
          network: '{{ .Values.network }}'
          consensusRpc: '{{ .Values.consensusRpc }}'
          executionRpc: '{{ .Values.executionRpc }}'

      - persistence:
          enabled: true
          size: 10Gi
          storageClass: local-path

      - ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            nginx.ingress.kubernetes.io/use-regex: "true"
          hosts:
            - host: obol.stack
              paths:
                - path: /helios(/|$)(.*)
                  pathType: ImplementationSpecific
